"""
basic_consumer_case.py

Read a log file as it is being written. 
"""

#####################################
# Import Modules
#####################################

# Import packages from Python Standard Library
import os
import time

# Import functions from local modules
from utils.utils_logger import logger, get_log_file_path

#####################################
# Define a function to process a poker hand
# #####################################


def process_hand(log_file) -> None:
    """
    Read a log file and process each poker hand.

    Args:
        log_file (str): The path to the log file to read.
    """
    with open(log_file, "r") as file:
        # Move to the end of the file
        file.seek(0, os.SEEK_END)
        print("Waiting on the dealer to deal a hand...")

        # Use while True loop so the consumer keeps running forever
        while True:

            # Read the next line of the file
            line = file.readline()

            # If the line is empty, wait for a new log entry
            if not line:
                # Wait a second for a new log entry
                delay_seconds = 1
                time.sleep(delay_seconds)
                # Keep checking for new log entries
                continue

            # We got a new poker hand!
            # Remove any leading/trailing white space and log the poker hand
            hand = line.strip()
            print(f"New poker hand: {hand}")

            # Check for a royal flush in the poker hand
            royal_flush = {"10", "J", "Q", "K", "A"}
            hand_set = set(hand.split())

            if royal_flush.issubset(hand_set):
                print(f"ALERT: We got a royal flush! \n{hand}")
                logger.warning(f"ALERT: The royal flush was found! \n{hand}")



#####################################
# Define main function for this script.
#####################################


def main() -> None:
    """Main entry point."""

    logger.info("START...")

    # Call the function we imported from utils/utils_logger module
    # to get the path to the log file being generated by the producer.
    # Assign the return value to a local variable.
    log_file_path = get_log_file_path()
    logger.info(f"Reading file located at {log_file_path}.")

    try:
        # Try to call the process_hand function with the log file path
        # as an argument. We know things will go wrong
        # eventually when the user stops the process, so we use a try block.
        process_hand(log_file_path)

    except KeyboardInterrupt:
        print("User stopped the process.")

    logger.info("END.....")


#####################################
# Conditional Execution
#####################################

# If this file is the one being executed, call the main() function
if __name__ == "__main__":
    main()
